server:
  port: 8888
  servlet:
    context-path: /api

spring:
  application:
    name: netexpert

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.xrnjiwuvobgqdzscqgqm
    password: Dd150805
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: SupabaseConnectionPool

  jpa: 
    hibernate: 
      ddl-auto: none
    show-sql: false
    
jwt:
  signerKey: "BGcYFW6KS7aIRLOL/zkNp+W/S1fMfqbCIx0dPRMTvCTETymBCq08wdSR5ZWeMpWU"

local:
  AI_HTTP: "https://netexpert-aicore.onrender.com/api/v1/chat"

logging:
  level:
    org.springframework.security: DEBUG
